apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: mpetrov-grafanacluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: mpetrov-grafanacluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: mpetrov-grafanacluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: mpetrov-grafanacluster
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: mpetrov-grafanacluster-control-plane
  namespace: default
spec:
  eksClusterName: mpetrov-grafanaCluster
  region: eu-west-3
  sshKeyName: capi-eks
  version: v1.30.5
  network:
    vpc:
      availabilityZoneUsageLimit: 2
      availabilityZoneSelection: Random
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: mpetrov-grafanacluster-pool-0
  namespace: default
spec:
  clusterName: mpetrov-grafanacluster
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: mpetrov-grafanacluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: mpetrov-grafanacluster-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: mpetrov-grafanacluster-pool-0
  namespace: default
spec: {}
