apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: mpetrov-wordpresscluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: mpetrov-wordpresscluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: mpetrov-wordpresscluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: mpetrov-wordpresscluster
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: mpetrov-wordpresscluster-control-plane
  namespace: default
spec:
  eksClusterName: mpetrov-wordpressCluster
  region: eu-west-3
  sshKeyName: capi-eks
  version: v1.31.4
  network:
    vpc:
      availabilityZoneUsageLimit: 2
      availabilityZoneSelection: Random
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: mpetrov-wordpresscluster-pool-0
  namespace: default
spec:
  clusterName: mpetrov-wordpresscluster
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: mpetrov-wordpresscluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: mpetrov-wordpresscluster-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: mpetrov-wordpresscluster-pool-0
  namespace: default
spec: {}
